### ISSUE TITLE
Github name

### ISSUE THREAD

**Issue by ichbindev** [ichbindev/ichbindev#1]
Hi @ichbindev would you be willing to change your github name so I can match it to my site and twitter?

**Comment by IchBinDev2** [comment]
Hey, klar. Ich helfe gerne. Kannst mir ja gerne ein kleines Trinkgeld auf Paypal dalassen, Email: jan.bredow@epeu.dev lmao

Nutzername wird jetzt geändert.

Hey, sure thing. I always help. You surely allowed to tip me on Paypal for this, Email: jan.bredow@epeu.dev

Username will change now.

**Comment by IchBinDev2** [comment]
Username has been changed. #close

**Comment by ichbindev** [comment]
Danke schön! Mein Deutsch ist noch nicht so toll, aber ich versuche. Ich bin sehr froh, den Neuen Namen zu haben.
